name: PortableFurnacePlus
main: com.nobstergo.portablefurnaceplus.PortableFurnacePlus
version: 1.0
api-version: 1.20
authors: [nobstergo]
commands:
  portablefurnaceplus:
    description: PortableFurnacePlus commands
    permission: portablefurnaceplus.admin
permissions:
  portablefurnaceplus.admin:
    default: op
